spring:
  profiles:
    active: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-payment:5432/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      "[hibernate.default_schema]": payment
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: kafka:29092
      group-id: payment-service-cg
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  application:
    name: paymentService
  cloud:
    consul:
      host: 172.1.1.17
      port: 8500
      discovery:
        serviceName: paymentService
        instance-id: "${spring.application.name}-127\u2022.0\u2022.0\u2022.1-${grpc.server.port}"
        register-health-check: false
        port: 9003
        tags: paymentService
      enabled: true

logging:
  level:
    org:
      apache:
        kafka: OFF

grpc:
  server:
    port: 9003

server:
  port: 8800
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  server:
    port: 8800
info:
  app:
    name: payment-service
    description: payment-service
#

# ---
#
# spring:
#   profiles:
#     active: local
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5435/postgres?binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
#     username: root
#     password: root
#   jpa:
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     show-sql: true
#   kafka:
#     listener:
#       missing-topics-fatal: false
#     producer:
#       value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#     consumer:
#       group-id: payment-service-cg
#       value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#       properties:
#         spring:
#           json:
#             trusted:
#               packages: "*"
#   cloud:
#     consul:
#       host: localhost
#       port: 8500
#       discovery:
#         serviceName: paymentService
#         instance-id: "${spring.application.name}-127\u2022.0\u2022.0\u2022.1-${grpc.server.port}"
#         register-health-check: false
#         port: 9003
#         tags: paymentService
#       enabled: true
#   application:
#     name: payment-service
#
# logging:
#   level:
#     org:
#       apache:
#         kafka: OFF
#
#
#
#
# grpc:
#   server:
#     port: 9003
#
#
#
# server:
#   port: 8800
# management:
#   endpoint:
#     health:
#       show-details: always
#   endpoints:
#     web:
#       exposure:
#         include: health,info
#   info:
#     env:
#       enabled: true
#   server:
#     port: 8800
# info:
#   app:
#     name: payment-service
#     description: payment-service
# midtrans:
#   serverkey: ${MIDTRANS_SERVERKEY}
