spring:
  profiles:
    active: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-subscription:5432/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      "[hibernate.default_schema]": subscription
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: kafka:29092
      group-id: subscription-service-cg
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  application:
    name: subscription-service

  cloud:
    consul:
      host: 172.1.1.17
      port: 8500
      discovery:
        serviceName: subscriptionService
        instance-id: "${spring.application.name}-127\u2022.0\u2022.0\u2022.1-${grpc.server.port}"
        port: 9000
        register-health-check: false
        tags: subscriptionservice
      enabled: true

logging:
  level:
    org:
      apache:
        kafka: OFF

grpc:
  server:
    port: 9000

server:
  port: 9100
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
  server:
    port: 9100
info:
  app:
    name: subscription
    description: subscription



# ---
#
# spring:
#   profiles:
#     active: local
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5430/postgres?binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
#     username: root
#     password: root
#   jpa:
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#
#   kafka:
#     listener:
#       missing-topics-fatal: false
#     producer:
#       value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#     consumer:
#       group-id: subscription-service-cg
#       value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#       properties:
#         spring:
#           json:
#             trusted:
#               packages: "*"
#   application:
#     name: subscription-service
#   cloud:
#     consul:
#       host: localhost
#       port: 8500
#       discovery:
#         serviceName: subscriptionService
#         instance-id: "${spring.application.name}-127\u2022.0\u2022.0\u2022.1-${grpc.server.port}"
#         port: 9000
#         tags: subscriptionservice
#         register-health-check: false
#       enabled: true
#
#
#
#
#
# logging:
#   level:
#     org:
#       apache:
#         kafka: OFF
#
# grpc:
#   server:
#     port: 9000
#     health-service-enabled: true
#
#
# server:
#   port: 9100
#
# management:
#   endpoint:
#     health:
#       show-details: always
##       group:
##         readiness:
##           include:
##             - grpcServer
##             - readinessState
#   endpoints:
#     web:
#       exposure:
#         include: health,info
#   info:
#     env:
#       enabled: true
#   server:
#     port: 9100
# info:
#   app:
#     name: subscription
#     description: subscription
