app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8082'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2

kafka:
  upload_topics_name: t.upload.request
  brokers: 
    - kafka:29092
  groupId: media-service-cg


rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'
